### ISSUE TITLE
Compare write performance without buffer

### ISSUE THREAD

**Issue by egeldenhuys** [egeldenhuys/prothesis#146]
Did the buffer improve performance? How much?

**Comment by CDuPlooy** [comment]
## Procrastinating af

If I remember correctly , a write is faster if you know the size of the buffer beforehand ; Glancing at your code quickly it looks like you could record the buffer's size ( assuming the target system can allocate that much memory ) and then just call write with the file descriptor , buffer and size.

As a side note , endl flushes the buffer which defeats the purpose of buffered i/o ( it's an expensive call ) - it might be better if you use << '\n' instead of << endl. 

Back to stats!

**Comment by egeldenhuys** [comment]
Preliminary tests show that the buffer reduced write time by about 500 microseconds. However Prothesis is designed to be run from a USB, which is much slower. Will test this as well.

**Comment by egeldenhuys** [comment]
The following tests led to the development of [disk-grapher](https://github.com/egeldenhuys/disk-grapher).
The results below are not guaranteed to be accurate or valid.

### Testing method

tests.cpp:

``` c++
...

t1 = high_resolution_clock::now();
for (int i = 0; i < passes; i++)
    UserDataSave.save(useBuffer);

t2 = high_resolution_clock::now();
duration = duration_cast<microseconds>( (t2 - t1) / passes ).count();

...
```

`1 μs = 1 * 10^-6 s`

### USB

`$ /lib64/ld-linux-x86-64.so.2 ./main_tests.out`

| # of Passes | Buffer | Average Time (μs) | Difference (μs) | (Average Time (s) |
| --- | --- | --: | --: | --: |
| 1 | Yes | 6,320 | - | 0.006 |
| 1 | No | 430,824 | 424,504 | 0.4 |
| 2 | Yes | 253,167 | - | 0.3 |
| 2 | No | 516,019 | 262,852 | 0.5 |
| 20 | Yes | 508,309 | - | 0.5 |
| 20 | No | 520,732 | 12,423 | 0.5 |

Notice the significant increase from 6,320 μs to 253,167 μs by adding an extra pass with the buffer

### HDD

 `./main_tests.out`

| # of Passes | Buffer | Average Time (μs) | Difference (μs) |
| --- | --- | --: | --: |
| 1 | Yes | 1,686 | - |
| 1 | No | 2,263 | 577 |
| 2,000 | Yes | 1,319 | - |
| 2,000 | No | 1,776 | 457 |

### Conclusion

The buffer decreased saving time by ~ 500 μs on the HDD, while on the USB is decreased by ~ 400,000 μs (0.4 s). This is a significant decrease in time when saving to a USB.
